fix: proper handling of LV and MV loads
ieeh-tu-dresden/powerfactory-utils pull request #21
Opened 2022-09-26 13:15 UTC by sasanjac

Fixes #7

2022-09-27 16:18 UTC, SebastianDD requested changes
small fixes

2022-09-28 06:00 UTC, SebastianDD approved these changes

2022-09-29 09:40 UTC, SebastianDD commented on powerfactory_utils/interface.py
> +            generator_name {Optional[str]} -- generator name if needed to specify independently (default: {None})
```suggestion
            generator_name {Optional[str]} -- name of generator or generator related object (e.g. external controller) if needed to specify independently (default: {None})
```

2022-09-29 15:38 UTC, SebastianDD commented on powerfactory_utils/exporter/exporter.py
> +                        name_suffix=sfx_pre.format(i) + "_FIXED",
```suggestion
                        name_suffix=sfx_pre.format(i) + "_" + ConsumerSystemType.FIXED.value,
```

2022-09-29 15:40 UTC, SebastianDD commented on powerfactory_utils/exporter/exporter.py
>          logger.debug(f"{load.loc_name}: there is no real rated, but s_r is calculated on basis of actual power.")
```suggestion
        logger.debug(f"{load.loc_name}: there is no real rated, but 's' is calculated on basis of actual power.")
```

2022-09-29 15:41 UTC, SebastianDD commented on powerfactory_utils/schema/topology/load.py
>              raise ValueError("Rated power `s_r` must be positive. Use type instead.")
```suggestion
            raise ValueError("Rated power `s` must be positive. Use type: LoadType instead.")
```

2022-10-02 08:05 UTC, SebastianDD commented on powerfactory_utils/exporter/exporter.py
> +                    scaling=scaling_cons,
```suggestion
                    scaling=scaling_prod,
```

2022-10-02 08:06 UTC, SebastianDD commented on powerfactory_utils/exporter/exporter.py
> +                    scaling=scaling_cons,
```suggestion
                    scaling=scaling_prod,
```

2022-10-02 08:59 UTC, SebastianDD commented on powerfactory_utils/exporter/load_power.py
> +    ) -> LoadPower:
```suggestion
    ) -> LoadPower:
    u = u / sqrt(3)  # for asymmetric calc, u_le has to be used instead of u_ll
```

2022-10-02 09:00 UTC, SebastianDD commented on powerfactory_utils/exporter/load_power.py
> +    ) -> LoadPower:
```suggestion
    ) -> LoadPower:
    u = u / sqrt(3)  # for asymmetric calc, u_le has to be used instead of u_ll
```

2022-10-02 09:31 UTC, SebastianDD commented on powerfactory_utils/exporter/exporter.py
> +        power_variable = LoadPower.from_pc_sym(
```suggestion
        power_variable = LoadPower.from_sc_sym(
```

2022-10-02 09:32 UTC, SebastianDD commented on powerfactory_utils/exporter/exporter.py
> +            p=load.cSav * LV_TO_BASE_POW,
```suggestion
            s=load.cSav * LV_TO_BASE_POW,
```

2022-10-02 09:33 UTC, SebastianDD commented on powerfactory_utils/exporter/exporter.py
> +        power_variable = LoadPower.from_pc_sym(
```suggestion
        power_variable = LoadPower.from_sc_sym(
```

2022-10-02 09:33 UTC, SebastianDD commented on powerfactory_utils/exporter/exporter.py
> +            p=load.cSav * LV_TO_BASE_POW,
```suggestion
            s=load.cSav * LV_TO_BASE_POW,
```

2022-10-02 10:04 UTC, SebastianDD commented on powerfactory_utils/exporter/exporter.py
> +                sfx_pre = " ({})"
```suggestion
                sfx_pre = "_({})"
```

2022-10-02 10:25 UTC, SebastianDD commented
further requested improvements
* round cosphi in topology and steadystate (expoter.py --> COSPHI_DECIMAL_DIGITS)
* round power in topology and steadystate (exporter.py --> no decimal digits)
* define separate names for parts of mv loads (e.g. MV_Load_5_CONSUMER and MV_Load_5_PROSUMER; otherwise in steadystate no unique assignment is possible (there exists then 2 entries with the same name))

2022-10-05 10:37 UTC, sasanjac commented
I implemented the requested improvements and changed the 7 bus network to the 8 bus network.

2022-10-08 11:21 UTC, SebastianDD approved these changes

2022-10-10 06:34 UTC, merged